export const fakeStories = [
    {
        image: '/images/dummy/blogs/blog-1.jpg',
        label: 'Инструкция',
        title: 'Как добавить объект на карту',
        author: 'SupportBot',
        publishedAt: '04.07.2025',
        views: 125,
        link: '/blog/how-to-add-object',
        buttonText: 'Читать инструкцию',
        content: 'Пошаговое руководство по добавлению объектов на интерактивную карту. Всё просто — следуйте этим шагам.',
    },
    {
        image: '/images/dummy/blogs/blog-2.jpg',
        label: 'Новость',
        title: 'Открыта бета-версия POI',
        author: 'Admin',
        publishedAt: '01.07.2025',
        views: 310,
        link: '/blog/beta-launch',
        content: 'Теперь вы можете протестировать проект в действии! Мы будем рады вашим отзывам и замечаниям.',
    },
    {
        image: '/images/dummy/blogs/blog-3.jpg',
        label: 'Гайд',
        title: 'Как пожаловаться на POI',
        author: 'Модерация',
        publishedAt: '03.07.2025',
        views: 89,
        link: '/blog/report-where-to-go',
        buttonText: 'Пожаловаться',
        content: 'Инструкция по отправке жалобы на неподходящий или ложный объект на карте. Помогите сделать сервис лучше.',
    },
    {
        image: '/images/dummy/blogs/blog-4.jpg',
        label: 'Поддержка',
        title: 'Часто задаваемые вопросы',
        author: 'SupportBot',
        publishedAt: '05.07.2025',
        views: 202,
        link: '/faq',
        content: 'Ответы на самые частые вопросы от пользователей: регистрация, добавление объектов, работа с картой и другое.',
    },
    {
        image: '/images/dummy/blogs/blog-5.jpg',
        label: 'Инструкция',
        title: 'Как добавить объект на карту',
        author: 'SupportBot',
        publishedAt: '04.07.2025',
        views: 125,
        link: '/blog/how-to-add-object',
        buttonText: 'Читать инструкцию',
        content: 'Пошаговое руководство по добавлению объектов на интерактивную карту. Всё просто — следуйте этим шагам.',
    },
    {
        image: '/images/dummy/blogs/blog-6.jpg',
        label: 'Новость',
        title: 'Открыта бета-версия POI',
        author: 'Admin',
        publishedAt: '01.07.2025',
        views: 310,
        link: '/blog/beta-launch',
        content: 'Теперь вы можете протестировать проект в действии! Мы будем рады вашим отзывам и замечаниям.',
    },
    {
        image: '/images/dummy/blogs/blog-1.jpg',
        label: 'Гайд',
        title: 'Как пожаловаться на POI',
        author: 'Модерация',
        publishedAt: '03.07.2025',
        views: 89,
        link: '/blog/report-where-to-go',
        buttonText: 'Пожаловаться',
        content: 'Инструкция по отправке жалобы на неподходящий или ложный объект на карте. Помогите сделать сервис лучше.',
    },
    {
        image: '/images/dummy/blogs/blog-2.jpg',
        label: 'Поддержка',
        title: 'Часто задаваемые вопросы',
        author: 'SupportBot',
        publishedAt: '05.07.2025',
        views: 202,
        link: '/faq',
        content: 'Ответы на самые частые вопросы от пользователей: регистрация, добавление объектов, работа с картой и другое.',
    },
];