import {Excursion} from "@/interfaces/Excursion";
import {PaidService} from "@/interfaces/PaidService";

export const excursionsPaidServices: PaidService[] = [
    {
        id: 1,
        title: "Американские горки 1+1",
        description: "Лесные американские горки на горе построены" +
            " в соответствии с рельефом, протяженностью около 1668 метров, это отличный элемент для снятия стресса или маленькой радости для ваших детей  Садитесь на скейт, катайтесь по бескрайнему лесу, крутые повороты, быстрые спуски...",
        image: "/images/dummy/excursions/excursion-paid-services/photo-1.jpg",
        price: "90 ¥",
    },
    {
        id: 2,
        title: "Канатный спуск",
        description: "Взлетев над землей, свободно перемещаясь между ущельями, кричите вслух о своих бедах, позволяя величественным и могучим пейзажам горы Пиеняньшань рассеять ваше плохое настроение. Не закрывайте глаза во время полета - вы рискуете упустить красоту глубокой долины",
        image: "/images/dummy/excursions/excursion-paid-services/photo-2.jpg",
        price: "90 ¥",
    },
    {
        id: 3,
        title: "Небесное зеркало",
        description: "Небесное зеркало. Путешествие, когда ты просто взял и поехал, - это мелочь. Оставить свой след в мире - это важно. Поделиться своей радостью с большим количеством людей - это достижение. Видео, фотографии и тексты могут запечатлеть красоту твоего путешествия",
        image: "/images/dummy/excursions/excursion-paid-services/photo-3.jpg",
        price: "50 ¥",
    }

];

export const excursions: Excursion[] = [
    {
        id: 1,
        title: "БОХАЙ в Хуньчуне",
        slug: "excursion-slug-1",
        image: "/images/dummy/excursions/excursion-1.jpg",
        images: [
            "/images/dummy/excursions/images-top/photo-1.jpg",
            "/images/dummy/excursions/images-top/photo-2.jpg",
            "/images/dummy/excursions/images-top/photo-3.jpg",
            "/images/dummy/excursions/images-top/photo-4.jpg",
            "/images/dummy/excursions/images-top/photo-5.jpg",
            "/images/dummy/excursions/images-top/photo-2.jpg",
            "/images/dummy/excursions/images-top/photo-3.jpg",
            "/images/dummy/excursions/images-top/photo-1.jpg",
            "/images/dummy/excursions/images-top/photo-2.jpg",
        ],
        includes: [
            "Автодром",
            "Аттракцион прыгающая лягушка",
            "Аттракцион самолеты",
            "Двухъярусная карусель",
            "Качели на высоте",
            "Колесо обозрения",
            "Пиратский корабль",
        ],
        description:
            "Во время экскурсии по Древнему городу Бохай вы сможете первыми прикоснуться к истории Трёх королевств. Погрузитесь в атмосферу процветающего города и великой страны — королевства Бохай эпохи",
        rating: 0,
        reviewsCount: 1,
        features: ["Прогулка на лодке"],
        link: "/excursions/excursion-slug-1",
        price: "58 ¥",
        priceFor: "за билет и экскурсию",
        category: {name: "парк", color: "pink"},
        facilities:
            [
                {id: 1, name: "Входной билет", iconUrl: "/images/icons/facilities/wifi.svg"},
            ],
        paidServices: excursionsPaidServices,
    },
    {
        id: 2,
        title: "”Веселый остров восток” в Хуньчуне",
        slug: "excursion-slug-2",
        image: "/images/dummy/excursions/excursion-2.jpg",
        images: [
            "/images/dummy/excursions/images-top/photo-1.jpg",
            "/images/dummy/excursions/images-top/photo-2.jpg",
            "/images/dummy/excursions/images-top/photo-3.jpg",
            "/images/dummy/excursions/images-top/photo-4.jpg",
            "/images/dummy/excursions/images-top/photo-5.jpg",
            "/images/dummy/excursions/images-top/photo-2.jpg",
            "/images/dummy/excursions/images-top/photo-3.jpg",
            "/images/dummy/excursions/images-top/photo-1.jpg",
            "/images/dummy/excursions/images-top/photo-2.jpg",
        ],
        includes: [
            "5D кинотеатр матрешка",
            "Американские горки",
            "Аттракцион прыгающая лягушка",
            "Двухъярусная карусель",
            "Качели на высоте",
            "Пиратский корабль",
        ],
        description:
            "Новый парк аттракционов \"Веселый остров восток” в Хуньчуне. Приглашаем вас на увлекательную экскурсию" +
            " из Хуньчуня в буддийский храм города Дуньхуа! Наше" +
            " путешествие начинается рано утром в 7:30, когда мы отправляемся на скоростной электричке",
        rating: 2.5,
        reviewsCount: 4,
        features: [
            "5D кинотеатр матрешка",
            "Автодром",
            "Американские горки",
            "Аттракцион огненное колесо",
            "Аттракцион прыгающая лягушка",
            "Аттракцион самолеты",
            "Аттракцион чашка",
            "Двухъярусная карусель",
            "Качели маятник",
            "Качели на высоте",
            "Колесо обозрения",
            "Пиратский корабль",
            "Пиратский корабль 2",
        ],
        link: "/excursions/excursion-slug-2",
        price: "500 ¥",
        priceFor: "за экскурсию",
        category: {name: "храм", color: "orange"},
        facilities:
            [
                {id: 1, name: "Входной билет", iconUrl: "/images/icons/facilities/wifi.svg"},
                {id: 2, name: "Обед", iconUrl: "/images/icons/facilities/hurricane-01.svg"},
                {id: 3, name: "проезд", iconUrl: "/images/icons/facilities/egg-fried.svg"},
            ],
        paidServices: excursionsPaidServices,
    },
    {
        id: 3,
        title: "”Веселый остров восток” в Хуньчуне",
        slug: "excursion-slug-2",
        image: "/images/dummy/excursions/excursion-2.jpg",
        images: [
            "/images/dummy/excursions/images-top/photo-1.jpg",
            "/images/dummy/excursions/images-top/photo-2.jpg",
            "/images/dummy/excursions/images-top/photo-3.jpg",
            "/images/dummy/excursions/images-top/photo-4.jpg",
            "/images/dummy/excursions/images-top/photo-5.jpg",
            "/images/dummy/excursions/images-top/photo-2.jpg",
            "/images/dummy/excursions/images-top/photo-3.jpg",
            "/images/dummy/excursions/images-top/photo-1.jpg",
            "/images/dummy/excursions/images-top/photo-2.jpg",
        ],
        includes: [
            "5D кинотеатр матрешка",
            "Американские горки",
            "Аттракцион прыгающая лягушка",
            "Двухъярусная карусель",
            "Качели на высоте",
            "Пиратский корабль",
        ],
        description:
            "Новый парк аттракционов \"Веселый остров восток” в Хуньчуне. Приглашаем вас на увлекательную экскурсию" +
            " из Хуньчуня в буддийский храм города Дуньхуа! Наше" +
            " путешествие начинается рано утром в 7:30, когда мы отправляемся на скоростной электричке",
        rating: 2.5,
        reviewsCount: 4,
        features: [
            "5D кинотеатр матрешка",
            "Автодром",
            "Американские горки",
            "Аттракцион огненное колесо",
            "Аттракцион прыгающая лягушка",
            "Аттракцион самолеты",
            "Аттракцион чашка",
            "Двухъярусная карусель",
            "Качели маятник",
            "Качели на высоте",
            "Колесо обозрения",
            "Пиратский корабль",
            "Пиратский корабль 2",
        ],
        link: "/excursions/excursion-slug-2",
        price: "500 ¥",
        priceFor: "за экскурсию",
        category: {name: "храм", color: "orange"},
        facilities:
            [
                {id: 1, name: "Входной билет", iconUrl: "/images/icons/facilities/wifi.svg"},
                {id: 2, name: "Обед", iconUrl: "/images/icons/facilities/hurricane-01.svg"},
                {id: 3, name: "проезд", iconUrl: "/images/icons/facilities/egg-fried.svg"},
            ],
        paidServices: excursionsPaidServices,
    },
    {
        id: 4,
        title: "”Веселый остров восток” в Хуньчуне",
        slug: "excursion-slug-2",
        image: "/images/dummy/excursions/excursion-2.jpg",
        images: [
            "/images/dummy/excursions/images-top/photo-1.jpg",
            "/images/dummy/excursions/images-top/photo-2.jpg",
            "/images/dummy/excursions/images-top/photo-3.jpg",
            "/images/dummy/excursions/images-top/photo-4.jpg",
            "/images/dummy/excursions/images-top/photo-5.jpg",
            "/images/dummy/excursions/images-top/photo-2.jpg",
            "/images/dummy/excursions/images-top/photo-3.jpg",
            "/images/dummy/excursions/images-top/photo-1.jpg",
            "/images/dummy/excursions/images-top/photo-2.jpg",
        ],
        includes: [
            "5D кинотеатр матрешка",
            "Американские горки",
            "Аттракцион прыгающая лягушка",
            "Двухъярусная карусель",
            "Качели на высоте",
            "Пиратский корабль",
        ],
        description:
            "Новый парк аттракционов \"Веселый остров восток” в Хуньчуне. Приглашаем вас на увлекательную экскурсию" +
            " из Хуньчуня в буддийский храм города Дуньхуа! Наше" +
            " путешествие начинается рано утром в 7:30, когда мы отправляемся на скоростной электричке",
        rating: 2.5,
        reviewsCount: 4,
        features: [
            "5D кинотеатр матрешка",
            "Автодром",
            "Американские горки",
            "Аттракцион огненное колесо",
            "Аттракцион прыгающая лягушка",
            "Аттракцион самолеты",
            "Аттракцион чашка",
            "Двухъярусная карусель",
            "Качели маятник",
            "Качели на высоте",
            "Колесо обозрения",
            "Пиратский корабль",
            "Пиратский корабль 2",
        ],
        link: "/excursions/excursion-slug-2",
        price: "500 ¥",
        priceFor: "за экскурсию",
        category: {name: "храм", color: "orange"},
        facilities:
            [
                {id: 1, name: "Входной билет", iconUrl: "/images/icons/facilities/wifi.svg"},
                {id: 2, name: "Обед", iconUrl: "/images/icons/facilities/hurricane-01.svg"},
                {id: 3, name: "проезд", iconUrl: "/images/icons/facilities/egg-fried.svg"},
            ],
        paidServices: excursionsPaidServices,
    },
    {
        id: 5,
        title: "”Веселый остров восток” в Хуньчуне",
        slug: "excursion-slug-2",
        image: "/images/dummy/excursions/excursion-2.jpg",
        images: [
            "/images/dummy/excursions/images-top/photo-1.jpg",
            "/images/dummy/excursions/images-top/photo-2.jpg",
            "/images/dummy/excursions/images-top/photo-3.jpg",
            "/images/dummy/excursions/images-top/photo-4.jpg",
            "/images/dummy/excursions/images-top/photo-5.jpg",
            "/images/dummy/excursions/images-top/photo-2.jpg",
            "/images/dummy/excursions/images-top/photo-3.jpg",
            "/images/dummy/excursions/images-top/photo-1.jpg",
            "/images/dummy/excursions/images-top/photo-2.jpg",
        ],
        includes: [
            "5D кинотеатр матрешка",
            "Американские горки",
            "Аттракцион прыгающая лягушка",
            "Двухъярусная карусель",
            "Качели на высоте",
            "Пиратский корабль",
        ],
        description:
            "Новый парк аттракционов \"Веселый остров восток” в Хуньчуне. Приглашаем вас на увлекательную экскурсию" +
            " из Хуньчуня в буддийский храм города Дуньхуа! Наше" +
            " путешествие начинается рано утром в 7:30, когда мы отправляемся на скоростной электричке",
        rating: 2.5,
        reviewsCount: 4,
        features: [
            "5D кинотеатр матрешка",
            "Автодром",
            "Американские горки",
            "Аттракцион огненное колесо",
            "Аттракцион прыгающая лягушка",
            "Аттракцион самолеты",
            "Аттракцион чашка",
            "Двухъярусная карусель",
            "Качели маятник",
            "Качели на высоте",
            "Колесо обозрения",
            "Пиратский корабль",
            "Пиратский корабль 2",
        ],
        link: "/excursions/excursion-slug-2",
        price: "500 ¥",
        priceFor: "за экскурсию",
        category: {name: "храм", color: "orange"},
        facilities:
            [
                {id: 1, name: "Входной билет", iconUrl: "/images/icons/facilities/wifi.svg"},
                {id: 2, name: "Обед", iconUrl: "/images/icons/facilities/hurricane-01.svg"},
                {id: 3, name: "проезд", iconUrl: "/images/icons/facilities/egg-fried.svg"},
            ],
        paidServices: excursionsPaidServices,
    },

];